backend: "donut"
max_batch_size: 16

dynamic_batching {
 max_queue_delay_microseconds: 100000
}

input [
  {
    name: "image"
    data_type: TYPE_UINT8
    dims: [384, 384, 3]
  }
]
output [
  {
    name: "text_sequence"
    data_type: TYPE_STRING
    dims: [1]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [0]
  }
]

parameters[
{
  key: "image_height"
  value: {
    string_value: "384"
  }
},
{
  key: "image_width"
  value: {
    string_value: "384"
  }
},
{
  key: "max_length"
  value: {
    string_value: "64"
  }
},
{
  key: "num_beams"
  value: {
    string_value: "5"
  }
},
{
  key: "prompt"
  value: {
    string_value: ""
  }
},
{
  key: "task_start_token"
  value: {
    string_value: "<s_500k>"
  }
},
{
  key: "prompt_end_token"
  value: {
    string_value: "<s_prompt>"
  }
}
]