backend: "yolo"
max_batch_size: 16

dynamic_batching {
 max_queue_delay_microseconds: 100000
}

input [
  {
    name: "image"
    data_type: TYPE_UINT8
    dims: [640, 640, 3]
  }
]
output [
  {
    name: "result"
    data_type: TYPE_STRING
    dims: [1]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [0]
  }
]

parameters[
{
  key: "image_height"
  value: {
    string_value: "640"
  }
},
{
  key: "image_width"
  value: {
    string_value: "640"
  }
},
{
  key: "conf"
  value: {
    string_value: "0.2"
  }
},
{
  key: "iou"
  value: {
    string_value: "0.2"
  }
},
{
  key: "rect"
  value: {
    string_value: "true"
  }
},
{
  key: "max_det"
  value: {
    string_value: "300"
  }
},
{
  key: "classes"
  value: {
    string_value: ""
  }
}
]